version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: digital_wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_database_data:/var/lib/postgresql/data

volumes:
  postgres_database_data: